### PR TITLE
Added first support for public transit API #113

### PR DESCRIPTION
**Pull request by Fluepke**
Pretty fast hack to get public transit up and running with susi.ai (currently at a hackathon)
Fixes: #113

### CODE REVIEW

**Comment by dynamitechetan** [comment]
This looks good but I think this can be done using some API like wolfram aplha in a SUSI dream. Also if we do it in a SUSI dream then future updates will be easier. 
I tried something similar just now http://dream.susi.ai/p/durationbetweenplaces

**Comment by saurabhjn76** [comment]
looks good, but as @dynamitechetan suggested a lightweight approach using SUSI dream would be easier to handle.

**Comment by Fluepke** [comment]
This is about supporting public transit (not some Maps API for driving with car) to susi, which is not possible as a susi dream. German railroad services do not offer a nice API for this. You need to parse ugly XML.
Actually, I was asked to push this, even though it's a hackathon project and not really ready so far (no testing, etc.)
I'd be fine if this gets rejected, so it can be pushed, when it's ready :)

**Comment by DravitLochan** [comment]
Nice Idea. I too was thinking to add a skill something similar. Please look for the merge conflicts

**Pull request closed without merging**
