### PR TITLE
reset password field in login if invalid credentials

### PR DESCRIPTION
**Pull request by DravitLochan**
Fixes issue #235 

Changes: Reset the pass element in login.js file

Screenshots for the change: 
screenshot from 2017-06-06 19-31-38

### CODE REVIEW

**Comment by DravitLochan** [comment]
1 commit for the pr, screenshot attached and relevant commit message. What else am I  skipping?

**Comment by DravitLochan** [comment]
@mariobehling Please merge.

**Comment by amitiwary999** [comment]
I am talking about commit message .

**Comment by DravitLochan** [comment]
I think it goes quite well with the corresponding issue

**Comment by DravitLochan** [comment]
@mariobehling please review and merge

**Pull request merged**
