### PR TITLE
Allow fetching chatbots using access token

### LINKED ISSUE #859: Save the chatbots created by a user
**Expected Behaviour**

In issue https://github.com/fossasia/susi_skill_cms/issues/744, users will be able to create multiple chatbots and these bots will be saved in the server. So, we need to:
- Identify each and every bot uniquely using a unique ID.
- Save the chatbot. (Chatbot is private/protected skills)
- Fetch these chatbots and show them to user.

The private/protected skill will be stored in the separate repository now after PR https://github.com/fossasia/susi_server/pull/870 but we need to keep track of the chatbots created by particular user. This is the purpose of this issue.

**Screenshots of the issue**

The bots will be shown in form of cards. It'll be similar to the following screenshot of [landbot.io](landbot.io).
screen shot 2018-06-19 at 4 01 53 pm

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by DNS-404**
Fixes #859 

Changes: 
Allow fetching of chatbots (private skills) from `data/chatbot/chatbot.json`. The parameters are `private` and `access_token`.
Can be tested at: `http://127.0.0.1:4000/cms/getSkillList.json?private=1&access_token=accessTokenHere`

If `chatbot.json` contains:
```
{"c9b58e182ce6466e413d5acafae906ad": {"chatbots": [
  {
    "name": "testing111",
    "language": "en",
    "group": "Knowledge"
  },
  {
    "name": "DNS_Bot",
    "language": "en",
    "group": "Knowledge"
  }
]}}
```

Then, the JSON received at `http://127.0.0.1:4000/cms/getSkillList.json?private=1&access_token=JwTlO8gdCJUns569hzC3ujdhzbiF6I` is:
```
{
  "session": {"identity": {
    "type": "email",
    "name": "test@whatever.com",
    "anonymous": false
  }},
  "chatbots": [
    {
      "name": "testing111",
      "language": "en",
      "group": "Knowledge"
    },
    {
      "name": "DNS_Bot",
      "language": "en",
      "group": "Knowledge"
    }
  ],
  "accepted": true,
  "message": "All chatbots of user fetched."
}
```

### CODE REVIEW

**Comment by DNS-404** [comment]
@Akshat-Jain @hkedia321 @Orbiter @akshatnitd 
I made the requested changes. Please review.

**Comment by DNS-404** [comment]
@Orbiter @mariobehling @hkedia321 I have a concern here regarding this PR. Earlier we added a parameter `protected` to all the skills to mark whether they are public or private/protected (a bot) but now the `susi_private_skill_data` repository is being made to store the private skills separately (due to PR [#870](https://github.com/fossasia/susi_server/pull/870) (merged) ). So, for fetching these skills, should I do it by checking the `protected` or should I fetch it from `susi_private_skill_data` repository? In the later case, I don't think that we need `protected` parameter anymore then. Please tell me your views on this. Thanks!

**Comment by Orbiter** [comment]
the `protected` attribute was called so because it was not the correct concept to enable private skills. But it was nevertheless an interesting concept which may be required for commercial applications within the environment of professional software development where an administrator (the author of the skill) can block changes by other authors. So we should keep the `protected`attribute but it is fully unrelated to private skills. That means we don't have a problem here.

**Comment by DNS-404** [comment]
@Orbiter I have used `private=1` to identify private skills separately as this has been used in other servlets like `CreateSkillService.java` as well.

**Comment by DNS-404** [comment]
@hkedia321 I updated the PR as per #909. Please review.

**Comment by DNS-404** [comment]
@Orbiter Please review.

**Comment by hkedia321** [comment]
@DNS-404 can you please provide a sample json output. Thanks.

**Pull request merged**
