### PR TITLE
resolving issues #1408

### PR DESCRIPTION
**Pull request by Lucifer0x17**
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]

Changes: [Add here what changes were made in this issue and if possible provide links.]

 @Dilshaad21 Can you please check and let me know?

### CODE REVIEW

**Comment by norbusan** [comment]
Sorry, this PR is completely bogus out of many reasons:

- PR needs to be done against the `development` branch
- this PR does not **move** the html files, it just adds copies of them
- it does not guarantee that the susi server finds the files and building and deployment works

The issue clearly states

> Move /html folder to /src/html and update any dependencies

that is not copy all files, and the dependencies need to be fixed, too. Furthermore, making sure that it works is integral part of it.

I leave it up to @Orbiter but I would close the PR straight away.

**Comment by Lucifer0x17** [comment]
@norbusan Can you explain a little. I'm new to open source so it's little confusing.

**Comment by mariobehling** [comment]
@Lucifer0x17 I recommend you take up an easier issue to start with. We do not have the bandwidth to teach all the steps to resolve this issue unfortunately. Thanks for your interest. Hope to see you continuing your first steps in FOSS! Thank you.

**Comment by Lucifer0x17** [comment]
okay! @mariobehling Thanks for your support.

**Pull request closed without merging**
