### PR TITLE
Add Heroku Deployment

### LINKED ISSUE #7: Automatically deploy susi_server to Heroku with travis
Other FOSSASIA projects get deployed automatically to Heroku after pull requests. Please implement the same.

I have set up an app already here: https://susi-server.herokuapp.com

### PR DESCRIPTION
**Pull request by BrainBuzzer**
Added automatic deployment from travis. @mariobehling Please add the secret key in the place with given command. Partially Fixes #7.

### CODE REVIEW

**Comment by BrainBuzzer** [comment]
@mariobehling can you please check this?

**Comment by mariobehling** [comment]
ok, let's try if it works. Thanks!

**Comment by mariobehling** [comment]
Travis not passing suddenly. I wonder why not.

**Comment by mariobehling** [comment]
But it is working on https://susi-server.herokuapp.com

Good job!

**Pull request merged**
