### PR TITLE
changed loklak to susi in app.json

### PR DESCRIPTION
**Pull request by DravitLochan**
progress on #175 

Changes: replaced susi with loklak in app.json file

### CODE REVIEW

**Comment by DravitLochan** [comment]
@jyoth1raditya @dynamitechetan @chashmeetsingh Please review!

**Comment by DravitLochan** [comment]
@mariobehling Updated the pr.

**Comment by aksh98** [comment]
@mariobehling @Orbiter The buildpack url doesn't seem correct. Kindly look into it. Should I send a PR?

**Comment by aksh98** [comment]
@mariobehling  @Orbiter The buildpack url in app.json doesn't seem correct. Kindly look into it. 
PS: I can work on this if needed.

**Comment by DravitLochan** [comment]
@aksh98 You can start with opening an issue with reference to this pr and send the corrected one.

**Pull request merged**
