### PR TITLE
Fixes issue #159, Deploying of Susi with kubernetes

### PR DESCRIPTION
**Pull request by jyoth1raditya**
Fixes issue #159, Deploying of Susi with kubernetes.
Changes are made to port address.
@mariobehling

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
@jyoth1raditya always update your forked repo first then make changes, followed by a PR :)
Squashing the commits is required.

**Comment by betterclever** [comment]
@jyoth1raditya I guess one should build Susi Server docker image manually and use Google Container Registry to store it rather than pulling it from your dockerhub, reason being:
- It allows developers to roll out updates quickly to their deployment once they made changes locally for other fellow developers to test it out.
- Your dockerhub image may not always remain in sync with latest code at Susi Server Repository leading to old deployments.

Though, your deployment is fine for someone testing out Susi but not fine for development.

I wrote a medium post (currently in draft) about what , according to me, should be the ideal process.
https://medium.com/@pranjalpaliwal/deploying-susi-on-google-cloud-with-kubernetes-438779b23a09

@chashmeetsingh @uday96 @dynamitechetan Please share your views about it.

**Comment by chashmeetsingh** [comment]
Agreed👍

**Comment by jyoth1raditya** [comment]
@betterclever. There is auto sync feature in dockerhub which periodiically changes docker image w.r.t its parent git repository.

**Comment by chashmeetsingh** [comment]
@jyoth1raditya then why not use the fossasia account here instead?

**Comment by betterclever** [comment]
@jyoth1raditya Ok fine. Second Point stands cancelled but still first point is major imo .

**Comment by jyoth1raditya** [comment]
@mariobehling, I am unable create dockers from fossasia account (I am member of organization created in dockerhub). So I need credential of account to make changes. Or any other enabling way.

**Comment by jyoth1raditya** [comment]
@betterclever, Thanks to @uday96 👍 . This procedure finally works. :)

**Comment by betterclever** [comment]
@jyoth1raditya @uday96 I'm missing out context please. Which procedure is being referenced by 'this' and 'that' in above conversation? Also, I know that @jyoth1raditya procedure is perfectly fine, but not good enough for developers to test out changes quickly (first point).

**Comment by chashmeetsingh** [comment]
@jyoth1raditya Check this and try?

screen shot 2017-05-14 at 7 20 03 pm

**Comment by jyoth1raditya** [comment]
@chashmeetsingh, In that procedure we need explicitly push every time there is a update.
Better we can sync github project with dockerhub image

**Comment by chashmeetsingh** [comment]
yup I asked for enabling the automatic build.

**Comment by uday96** [comment]
@jyoth1raditya In the installation procedure I dont think we need 
> 4.In the search bar above on console page, enter 'Compute Engine' and click on Compute Engine.
>5.If you have not activated billing for compute engine, click enable billing and choose your account to activate your Compute Engine. Your Google Compute Engine should be activated within a few minutes.

It works without that also. The initiall installation procedure for loklak server had that because we were creating a VM there. I dont think we need it here

**Comment by dynamitechetan** [comment]
@betterclever It worked 👍.

**Comment by dynamitechetan** [comment]
@jyoth1raditya when I tried to run ```kubectl run susi_server --image= docker-id --port=80``` it gave me a regex error. deployment name cannot have ```_```.  Please give it another name.

**Comment by chashmeetsingh** [comment]
@dynamitechetan change susi_server to susi-server and try

**Comment by dynamitechetan** [comment]
@chashmeetsingh I did that, I am just suggesting him to change it in the docs too.

**Comment by chashmeetsingh** [comment]
Please squash the commits.

**Pull request merged**
