### PR TITLE
Fixes #636 Update SUSI's detail of sub-projects in .yaydoc.yml

### LINKED ISSUE #636: Update SUSI's detail of sub-projects in .yaydoc.yml
**Actual Behaviour**
There are many sub projects of SUSI at https://github.com/fossasia?utf8=%E2%9C%93&q=susi&type=&language= which are not added in `.yaydoc.yml`
Please state here what is currently happening.

**Expected Behaviour**
Adding the missing repositories of SUSI
State here what the feature should enable the user to do.

**Steps to reproduce it**

Add steps to reproduce bugs or add information on the place where the feature should be implemented. Add links to a sample deployment or code.

**LogCat for the issue**

Provide logs for the crash here

**Screenshots of the issue**

Where-ever possible attach a screenshot of the issue.

**Would you like to work on the issue?**
**Yes**
Please let us know if you can work on it or the issue should be assigned to someone else.
**Assign me**

### PR DESCRIPTION
**Pull request by bhaveshAn**
Fixes #636 

Changes: [Add here what changes were made in this issue and if possible provide links.]
Added the missing repositories in `.yaydoc.yml`
Screenshots for the change:

### CODE REVIEW

**Comment by bhaveshAn** [comment]
@Orbiter @robbyoconnor Please review

**Comment by robbyoconnor** [comment]
@bhaveshAn is there a reason you tagged me?  

Tip: Don't tag random people.

**Comment by bhaveshAn** [comment]
> @bhaveshAn is there a reason you tagged me?

Suggestion came while tagging, thats why. Hope you don't mind

@mariobehling @imujjwal96 Please review

**Comment by bhaveshAn** [comment]
@mariobehling @imujjwal96 @the-dagger Please review

Thanks !!

**Pull request merged**
