### PR TITLE
Improving the gh-pagesUpdater script

### PR DESCRIPTION
**Pull request by Abhi2424shek**
Improved the gh-pagesUpdater script a lot, improved the documentation comments and tweaked the directories a bit for proper functioning.

@mariobehling please review and merge...

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you.

Please match the PR to an issue outlining why and what improvements are taking place. Cheers.

**Comment by Abhi2424shek** [comment]
@mariibehling no issues yet, it's just an update to the script it solves some bugs which may occur in some unusual cases

**Comment by jig08** [comment]
@Abhi2424shek Safe bet, open an issue and refer it here 😉

**Comment by Abhi2424shek** [comment]
@jig08 heres the issue then #64 ;)

**Pull request merged**
