### PR TITLE
Create API to store images locally

### LINKED ISSUE #806: Create API for storing custom theme images for botbuilder
**Actual Behaviour**

No API present for storing images (background image, bot icon image) required for custom design of the SUSI chatbot plugin.

**Expected Behaviour**

Develop an API for storing image.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by hkedia321**
Fixes #806 

Changes: 
- create API `/cms/uploadImage.json` to upload image. This API accepts three parameters in a POST request:
  - access_token
  - image_name
  - image (the image file)

It stores the image in local storage inside the `data/image_uploads/<user_id>` directory. 
Later, another API will be created to retrieve this stored image (#879)

Output of successful request:
```
{
    "image_path": "963e84467b92c0916b27d157b1d45328/1529692996805_susi icon.png",
    "accepted": true
}
```
Storage location of the image:
image

Where, the number `963e84467b92c0916b27d157b1d45328` is the user id of the user and `1529692996805` is generated by getting the System time in milliseconds. This helps to differentiate between images of same name uploaded by the same user. 
The client will get the `image_path` which can be stored in another location (say `userSettings`).
Then another API will be created to retrieve the image when the client sends this `image_path` (#879).

### CODE REVIEW

**Comment by hkedia321** [comment]
@Orbiter I have now made new folders for each user, so images will be stored in  `image_uploads/<user_email>/1528807028466_logo.png`. The random integer is generated by getting the system time so as to avoid overwriting of files with common names.

**Comment by hkedia321** [comment]
@anshumanv @akshatnitd @Akshat-Jain @AnupKumarPanwar @DNS-404 Please review.

**Comment by hkedia321** [comment]
@mariobehling @Orbiter currently there is no id for each user, as discussed in #592. So the only way to uniquely identify the user currently seems to be their email id.

**Comment by prateekiiest** [comment]
How about the specific ID be generated based on their birthdate?
@mariobehling @hkedia321

**Comment by Orbiter** [comment]
It's bad but we should clarify https://github.com/fossasia/susi_server/issues/592 first, agree on a new identification method and then use that ID as part of the path.
On hold.

**Comment by hkedia321** [comment]
@Orbiter @mariobehling I have now added `userId` instead of `userEmail`. Please review. Thanks.

**Comment by hkedia321** [comment]
@AnupKumarPanwar updated the description with the storage location screenshot. Please check.

**Comment by Orbiter** [comment]
@mariobehling The email path has been replaced by the new uuid.

**Pull request merged**
