### PR TITLE
Allowing build from any other branches

### LINKED ISSUE #627: Improve Caching in Travis Build
Improve Caching and Code Coverage

### PR DESCRIPTION
**Pull request by naveentherocker**
You can build from any other Branches
Fixes #627 627

### CODE REVIEW

**Comment by naveentherocker** [comment]
Well I have included Other Branches too

**Comment by sayak119** [comment]
@naveentherocker I think @0x48piraj wants to say that it may make other developers to think that gh-pages is special.

**Comment by naveentherocker** [comment]
But it's fine know? Should i make any changes? @sayak119

**Comment by naveentherocker** [comment]
@ms10398 Is it fine now?

**Pull request closed without merging**
