### PR TITLE
Added API endpoint to get github user content path

### LINKED ISSUE #564: API Endpoint to get URL of the Skills Repository
In CMS we are using 
>     let image = 'https://raw.githubusercontent.com/fossasia/susi_skill_data/master/models/general/
Instead of hard coding this we need to send it from the server.

**Would you like to work on the issue?**
Yes. I am working on this issue.

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes #564

can be tested on 
http://127.0.0.1:4000/cms/getSkillDataUrl.json

### CODE REVIEW

**Comment by dynamitechetan** [comment]
@saurabhjn76 @DravitLochan  @madhavrathi please review

**Comment by mariobehling** [comment]
Is this only about "get github user content path"? We are using "git" and simply sync with "github". Please ensure we are linking with the actual git component for SUSI.AI server and not just github.

**Comment by dynamitechetan** [comment]
@mariobehling yes, this API endpoint works on the git component of SUSI.AI not just GitHub.

**Comment by tstreamDOTh** [comment]
@dynamitechetan The api end point is returning a wrong url for skill image. There seems to be a typo. Could you check?

**Pull request merged**
