### PR TITLE
ShowAdminServie servlet

### PR DESCRIPTION
**Pull request by DravitLochan**
Fixes issue #474 

Changes: added ShowAdminService.java file

### CODE REVIEW

**Comment by DravitLochan** [comment]
@dynamitechetan @saurabhjn76 @Orbiter @mariobehling Please review and merge.

**Comment by DravitLochan** [comment]
@hpdang We were told to add this copyright to all the API end pints which belong to aaa package. Should I still remove it?

**Comment by mariobehling** [comment]
> We were told to add this copyright to all the API end pints which belong to aaa package. Should I still remove it?

@DravitLochan Please point me to the discussion. If there is a copyright message, it should be addressed to the project and not a single contributor. I am unclear in what way there should be a copyright message here and I would tend to avoid a specific copyright info here.

**Comment by DravitLochan** [comment]
@mariobehling Could not find the discussion. It was a PR AFAIK. Removed it. Will also remember not to add it from next time onwards. apologies!!

**Pull request merged**
