### PR TITLE
Feat: Delete Skill Stores a deleted skill for 30 days

### LINKED ISSUE #486: Update Delete Skill Endpoint
1. Delete Skill Endpoint should also be able to delete a skill. The skill should be moved to an area "deleted skills" and be deleted automatically after 30 days.
2. Admins should have an option to re-add the skill within that period as well.

### PR DESCRIPTION
**Pull request by dynamitechetan**
Fixes #486  
Delete Skill Endpoint is now able to delete a skill. 
The skill should be moved to an area "deleted skills" and be deleted automatically after 30 days.
http://127.0.0.1:4000/cms/deleteSkill.txt?skill=gender

### CODE REVIEW

**Comment by mariobehling** [comment]
@dynamitechetan Please explain where are the skills stored in the meantime for the 30 days in the repository? Are you adding a "delete" tag or move them to a dedicated "delete" folder? Please add the relevant info to the documentation.

**Comment by dynamitechetan** [comment]
@mariobehling When someone deletes a skill then it will move a folder ```delete_skills_dir```.
When a file is moved to the ```delete_skills_dir``` its last modified date is changed to the current date.
Then in the caretaker there is a function which checks for files which are older than 30 days by checking the last modified date.
If there is any file which is older than 30 days then it deletes them.

**Comment by mariobehling** [comment]
Ok, got it. Thanks!

**Comment by mariobehling** [comment]
@dynamitechetan Add this info to the documentation in following PRs, please.

**Pull request merged**
