### PR TITLE
Added Console Rule App

### LINKED ISSUE #29: Create a Console Rule Learning App
We want to be able to make it easy to create new console rules. Those rules are the method to attach external knowledge to susi. To check and store new console rules, there is now the rule learning backend api, the details are described here: https://github.com/fossasia/susi_server/blob/development/src/org/loklak/api/learning/ConsoleLearning.java#L45-L163

To store a new console rule, the user has to enter at least the following entries:
- the external json API address
- an example input for that API
- a name for the new console rule

Furthermore, the user must submit a jsonpath which points into a result array within the JSON from the console API. The new back-end process supports the user by finding that jsonpath automatically.

What we need:
- an input window for those three options
- a 'verify' button which calls the backend. That will return a lot of information together with the jsonpath which the user can edit. 
- a 'store' button which can be used when the user is satisfied with the back-end verififaction.

### PR DESCRIPTION
**Pull request by BrainBuzzer**
Fixes #29. Please tell me if I have to improve anymore. I am trying to it a little fast as I don't want to miss out other GCI Tasks. Will definitely be doing more work on UI.

### CODE REVIEW

**Comment by jig08** [comment]
Provide the link to live demo or relevant screenshot for easier review.

**Comment by BrainBuzzer** [comment]
I always forget. Sorry

**Comment by BrainBuzzer** [comment]
Right side displays lists the rules. And helps in deleting them.

**Comment by jig08** [comment]
Live demo link shall be better :)

**Comment by BrainBuzzer** [comment]
Ok but since I am away from pc, I'll update that tomorrow morning. Guess I would complete 2 tasks at a time.

**Comment by samsruti** [comment]
@BrainBuzzer Quality is far better than that of Quantity. Focus on the quality more. Thanks :)

**Comment by BrainBuzzer** [comment]
Yeah. I have a bitter experience of that last year. This year I am putting quality first. But tasks are vanishing out fast, so I have to choose hard ones.

**Comment by BrainBuzzer** [comment]
https://damp-harbor-15292.herokuapp.com/ Here you go.

**Comment by BrainBuzzer** [comment]
https://damp-harbor-15292.herokuapp.com/apps/consolerule to be more specific. You need to login in order to do it successfully.

**Comment by jig08** [comment]
Looks clean , +1.

**Comment by BrainBuzzer** [comment]
@daminisatya can you please check this?

**Comment by BrainBuzzer** [comment]
@samsruti I guess putting quality over quantity was definitely not a good idea.

**Pull request merged**
