### PR TITLE
Added param explanation

### LINKED ISSUE #558: Lacking documentation
There are some files which doesn't have proper param definition. This also doesn't look consistent as some functions have and some have not. This issue resolves that problem.

Files affected:
* `src/ai/susi/server/AbstractAPIHandler.java`
* `src/ai/susi/server/ClientConnection.java`

### PR DESCRIPTION
**Pull request by yashLadha**
Fixes #558

### CODE REVIEW

**Comment by yashLadha** [comment]
@madhavrathi  can u help me resolving the codecov issue.

**Comment by dynamitechetan** [comment]
Please ignore codecov. Just make sure Travis passes.

**Comment by madhavrathi** [comment]
@yashLadha Please ignore codecov for now. Travis is important

**Comment by yashLadha** [comment]
Is the commit message is satisfactory or not?

**Pull request merged**
