### PR TITLE
Generated a documentation site for susi server

### PR DESCRIPTION
**Pull request by adarsh-ideal**
Generated a documentation site for susi server from README.md and other .md files inside docs folder.
Check this issue for further information: https://github.com/fossasia/susi_server/issues/30
Generated site can be seen at: https://adarsh-ideal.github.io/susi_server/

### CODE REVIEW

**Comment by mariobehling** [comment]
Thank you. Please take out "susi_server is maintained by adarsh-ideal. This page was generated by GitHub Pages."

Cheers.

**Comment by mariobehling** [comment]
It also shows 378 files changed. This large number makes it difficult to review. Please rebase this PR.

**Comment by adarsh-ideal** [comment]
Thanks!
Well the title will change after getting merged. There will be fossasia instead of adarsh-ideal.

And 
Out of 378 files changed:
1. 376 deleted ( they were susi server application files, not required for documentation purpose )

2. 1 file changed ( Readme.md to link with other .md files )

3. 1 file added ( _config.yml to set the theme for github pages site )

**Comment by mariobehling** [comment]
Ah yes. You are right. Sorry about the confusion. Cheers.

**Comment by mariobehling** [comment]
@adarsh-ideal Would you be interested to generate the same site for loklak? Issue is here: https://github.com/loklak/loklak_server/issues/895

**Comment by adarsh-ideal** [comment]
@mariobehling Thank you :-)
Yeah sure, I'll do that.

**Pull request merged**
