### PR TITLE
Fixes 25: Partially: Change in basic Texts

### PR DESCRIPTION
**Pull request by samsruti**
https://github.com/fossasia/susi_server/issues/25
 Partially,  Change api.asksusi.com to Home and Change in Top bar Menu item name Apps to Account

### CODE REVIEW

**Comment by mariobehling** [comment]
Thanks.

**Comment by mariobehling** [comment]
@samsruti could you help us to make this system run on Heroku for automatic deployments as well? https://susi-server.herokuapp.com

**Comment by samsruti** [comment]
@mariobehling Yeah sure I could try for this :)

**Comment by samsruti** [comment]
@mariobehling Which branch do I need to automate for Heroku deployment? master or development?

**Comment by mariobehling** [comment]
development.

**Comment by samsruti** [comment]
Sure thanks :)

**Comment by samsruti** [comment]
@mariobehling susi-server is not available. We need something else.

**Comment by mariobehling** [comment]
@samsruti Susi on Heroku currently does not work. Would be great if you could help to make it work. Maybe fork it and try to make it on your personal Heroku account work first, if you can. Cheers.

**Comment by samsruti** [comment]
Yeah sure will let you know as soon i completed the deployment :)

**Pull request merged**
