### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by sk1999**
Updated  README.srt  #519 

Changes:Edited README.srt

### CODE REVIEW

**Comment by betterclever** [comment]
@sk1999 Please mention the issue number correctly.

**Comment by sk1999** [comment]
@betterclever I am sorry will take care of it from next time.

**Comment by betterclever** [comment]
@sk1999 Please update this PR also.

**Comment by sk1999** [comment]
@betterclever Done.Is it all right now?

**Comment by betterclever** [comment]
@sk1999 You are referencing the pull request itself. Please point to an issue. Our workflow includes matching each PR with a corresponding issue.

**Comment by sk1999** [comment]
@betterclever The issue here is very small so I do not know how I should point my PR to an issue.
Please suggest me what to do. Thanks

**Comment by betterclever** [comment]
@sk1999 It is our normal workflow to go through issues. Please take care from next PR. :+1:

**Comment by sk1999** [comment]
@betterclever Thanks

**Pull request merged**
