### PR TITLE
Fixes:#1235 render correct messages on local host

### PR DESCRIPTION
**Pull request by dernDren161**
Fixes #1237 

Changes: The server now gives correct response message

Screenshots for the change:

### CODE REVIEW

**Comment by dernDren161** [comment]
@Orbiter Sir, i didn't touch those files but still changes are being made to the 2 files, i don't know why . I'll try again rectifying this with another commit!

**Comment by Orbiter** [comment]
these changes in the build file always create a mess in my set-up. Please remove the changes from the pull request.

**Comment by dernDren161** [comment]
@Orbiter sir are you mentioning about the already merged PR? would there be any further fixes that could make it work well or should i straight away delete the patch?

**Comment by dynamitechetan** [comment]
Hey @dernDren161, you have modified the ```.classpath``` file.  Since there are changes only in ```PasswordChangeService.java``` so please commit that file only.

**Comment by Orbiter** [comment]
This commit contains 2 files of changes for .classpath and .gitignore and that should not be part of a pull request for one single file. This cannot be merged.

**Pull request closed without merging**
