### PR TITLE
moved group endpoints to aaa

### PR DESCRIPTION
**Pull request by saurabhjn76**
Fixes issue #338 

Changes: refractor group endpoints to aaa, added boolean flags

Screenshots for the change: 
N\A

### CODE REVIEW

**Comment by saurabhjn76** [comment]
@DravitLochan @dynamitechetan please review

**Comment by saurabhjn76** [comment]
@mariobehling please review and merge

**Comment by mariobehling** [comment]
@saurabhjn76 Please resolve merge conflicts.

**Comment by saurabhjn76** [comment]
@mariobehling done

**Pull request merged**
