### PR TITLE
Issue#175, updated loklak references to susi server

### PR DESCRIPTION
**Pull request by saurabhjn76**
deals with issue #175 

Changes: 

-  Updated Installation of Susi Server with Docker on Bluemix

- Updated Deploying Susi server with Kubernetes on Google Cloud

### CODE REVIEW

**Comment by mariobehling** [comment]
@saurabhjn76 Please actively ask your co-developers for reviews using the "@" feature and on the chat. Let's work together to speed up the review and merge process!

**Comment by saurabhjn76** [comment]
@Fluepke thanks, will resolve them and update the PR soon

**Comment by Fluepke** [comment]
Thank you for also solving the other issues 👍👍

**Comment by saurabhjn76** [comment]
@Fluepke made some changes please review.

**Pull request merged**
