### PR TITLE
Include documentation files from root while fixing relative links for sphinx documentation

### LINKED ISSUE #120: Links not correct on gh-pages live page
Some links are giving 404s and the logo is not showing up.

Please fix the links by updating the way the gh-pages branch is build. Please ensure the links are set in a generic way.

### PR DESCRIPTION
**Pull request by pri22296**
Fixes #120

### CODE REVIEW

**Comment by yukiisbored** [comment]
@pri22296 Can you give us a comparison of the file before and after?

**Comment by pri22296** [comment]
@yukiisbored  you can check out the comparison report in the following link

https://www.diffnow.com/?report=wn3mr

**Comment by yukiisbored** [comment]
@pri22296 Since Sphinx doesn't require `.html` for linking other articles. Just remove the `.html` suffix. Also as a suggestion, please make your code more clear of what it does. It should be readable without digging in.

**Comment by pri22296** [comment]
@yukiisbored I have removed the .html suffix from the links. I have also added some docstrings/comments in my code wherever applicable. Thanks for your suggestions.

**Pull request merged**
