### PR TITLE
fix : Link added for action type anchor and query where am I

### PR DESCRIPTION
**Pull request by chiragw15**
Fixes issue #304 
Changes: changed "lat" to latitude and "lon" to longitude. Seems to work.

### CODE REVIEW

**Comment by mariobehling** [comment]
Travis is failing. Please check.

**Comment by chiragw15** [comment]
@mariobehling Travis is passing. Codecov is failing and I have no idea why. Don't know if codecov is even set up properly. Seems to fail for almost every PR.

**Comment by chiragw15** [comment]
@dynamitechetan @saurabhjn76 Can you guys help me with this? I don't know why codecov is failing.

**Comment by mariobehling** [comment]
@chiragw15 Ok, I restarted travis and it worked the second time.

Let's follow up on codecov. Merging this now.

**Pull request merged**
