### PR TITLE
Updated Travis CI

### LINKED ISSUE #627: Improve Caching in Travis Build
Improve Caching and Code Coverage

### PR DESCRIPTION
**Pull request by naveentherocker**
Fixes #627

### CODE REVIEW

**Comment by naveentherocker** [comment]
Why Codecov is not reviewing?

**Comment by naveentherocker** [comment]
@daminisatya Now it's fine. @fossasia/susi-ai-devops Please Review

**Comment by naveentherocker** [comment]
@daminisatya It's better if you could merge my PR or @abishekvashok 's PR Quickly. Because there may be some Conflicts. So We can Resolve them

**Comment by daminisatya** [comment]
@the-dagger Can you provide me write access to susi server please :)

**Comment by the-dagger** [comment]
Done.

**Pull request merged**
