### PR TITLE
Universal Build

### LINKED ISSUE #31: Issue running susi server
I am unable to run susi server, I have followed the procedures mentioned in the Readme. I have built it using gradle.

Here are the logs.
Viveks-MacBook-Pro:bin devenv$ ./start.sh
susi detected that you did not yet run the installation wizard.
It let's you setup an administrator account and a number of settings, but is not mandatory.
You can manually start it by running bin/installation.sh
starting susi
susi server failed to start. See data/loklag.log for details. Here are the last logs:
Error: Could not find or load main class org.loklak.SusiServer
Viveks-MacBook-Pro:bin devenv$

### PR DESCRIPTION
**Pull request by vivekkiran**
Fixed #31 , #39 and #40

### CODE REVIEW

**Comment by vivekkiran** [comment]
@mariobehling i have fixed all the conflicts

**Comment by Orbiter** [comment]
Hi @vivekkiran I tested your universal build changes some days ago and what I found is:
- the new build process works \o/
- the old start scripts do not work any more, any many external processes, especially in the production environment depend on that :(
- as you made not only changes to the build process, but also performed an automatic code cleanup (258 files changes) we now have constant conflicts with all the maintenance changes I do. This big code cleanup is not only not necessary to change the build process, it is also not wanted by me because it makes code change progress histories and monitoring of causes of code changes impossible.

Therefore I decided that I either take some time to use your changes using cherry-picking to ensure
- that the old application start scripts still work
- that the unnecessary changes are not included

Because such a cherry-picking task is currently for me out of time-scope, I cannot do that. Would it be possible for you to change your pull request in such a way, that conflicts do not appear becuase you do not change code where it is not necessary and to re-enable the old start scripts (bin/start.sh)? That would speed up the inclusion of your work!

**Comment by mariobehling** [comment]
@vivekkiran Would be great to follow up on the open points. What are your ideas?

**Comment by Abhi2424shek** [comment]
@vivekkiran updates would be awesome

**Comment by Abhi2424shek** [comment]
@sudheesh001 seems that @vivekkiran is unavailable for a long time, can you guys cherry pick, I don't have access to the system, it been a while!

**Comment by Orbiter** [comment]
in favor of https://github.com/fossasia/susi_server/issues/76 we should close this issue because it made too much changes in all of the code and not just a change to make the gradle build process possible.

**Comment by vivekkiran** [comment]
@Orbiter @mariobehling  @sudheesh001 @abhi007tyagi Sorry for late reply, I was unwell from past few days and then had lot of work and couldn't contribute to foss projects for some time. @Orbiter @sudheesh001 I will make changes according to your suggestions and issues #76 to #85 are somewhat related, so I will work on them.

**Pull request closed without merging**
