### PR TITLE
Fixes #193: Session time

### LINKED ISSUE #193: Session time
**Actual Behaviour**

Using the web app. 
You 18:33:47 What time is it
SUSI 18:33:48  it is 33 minutes past 16

**Expected Behaviour**
it is 18:33

Susi server has to be aware of the local sessions user time.

### PR DESCRIPTION
**Pull request by ByeongGil-Jung**
Fixes #193 

Changes: Modified to return the current time
- 'conf/system_skills/general/en/en_0200_facts_knowledge.json'
- 'conf/system_skills/general/de/de_0200_fakten_wissen.json'

### CODE REVIEW

**Comment by ByeongGil-Jung** [comment]
Really thanks for replying my pull request !
But, currently I don't know how should I do.
Really sorry to bother you. 
But it's the first time that I contribute this nice opensource.
I think that I don't have any authentication that can access this pull request.
Could you give some way to resolve the current problem ?
Or do I need the authentication that access pull request ?

To nice developers, thanks for replying :) 👍

**Comment by AnupKumarPanwar** [comment]
@ByeongGil-Jung Hope you are familiar with what merge conflicts are. Merge conflicts happen when you merge branches that have competing commits, and Git needs your help to decide which changes to incorporate in the final merge. So you must update the conflicting files and commit again.

**Comment by ByeongGil-Jung** [comment]
Okay, I've merged the original branch.
Really thank you for advise to me how to resolve the problem. :)

**Comment by ByeongGil-Jung** [comment]
Okay, I modified it ! :)

**Comment by ByeongGil-Jung** [comment]
Thank you for advise to me. I've squashed it !

**Pull request merged**
