### PR TITLE
Download all files in data/settings

### PR DESCRIPTION
**Pull request by DravitLochan**
First step #112 
Changes: added a servlet  that zips and downloads data/settings folder
Test locally here -> http://127.0.0.1:4000/data/settings

### CODE REVIEW

**Comment by DravitLochan** [comment]
@Orbiter @dynamitechetan @saurabhjn76 Please review!

**Comment by DravitLochan** [comment]
okay! the issue did not state this so I miss took that point. Sorry for the inconvenience. Working on it to make it in accordance.

**Comment by DravitLochan** [comment]
@Orbiter Changed the servlet accordingly. Please review!

**Comment by Orbiter** [comment]
Ok

**Comment by Orbiter** [comment]
Ok

**Comment by DravitLochan** [comment]
@Orbiter @mariobehling Please merge!

**Pull request merged**
